"""
Chatbot API routes.
Request/response schema unchanged for frontend compatibility.
No business logic here; all logic in RAGService.
"""
from datetime import datetime
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.core.logging_config import log_chatbot_failure, log_chatbot_request, log_chatbot_success
from app.services.rag_service import RAGService

router = APIRouter()

# Lazy singleton for RAG service (created when OpenAI key is set)
_rag_service: Optional[RAGService] = None


def get_rag_service() -> Optional[RAGService]:
    global _rag_service
    if _rag_service is None:
        from app.core.config import settings
        if settings.OPENAI_API_KEY and settings.OPENAI_API_KEY.strip():
            from app.services.embedding_service import EmbeddingService
            from app.services.llm_service import LLMService
            _rag_service = RAGService(
                embedding_service=EmbeddingService(),
                llm_service=LLMService(),
            )
    return _rag_service


# --- Request/Response schemas (do not change for frontend) ---

class ChatMessageRequest(BaseModel):
    content: str
    session_id: str
    context: Dict[str, Any] = {}


class ChatMessageResponse(BaseModel):
    message: str
    session_id: str
    suggestions: Optional[List[str]] = None
    actions: Optional[List[Dict[str, Any]]] = None
    metadata: Optional[Dict[str, Any]] = None
    error: Optional[str] = None


class CreateSessionRequest(BaseModel):
    user_id: str


class CreateSessionResponse(BaseModel):
    session_id: str
    created_at: datetime


class ChatHistoryResponse(BaseModel):
    session_id: str
    messages: List[Dict[str, Any]]


@router.post("/message", response_model=ChatMessageResponse)
async def send_message(
    request: ChatMessageRequest,
    db: Session = Depends(get_db),
    rag: Optional[RAGService] = Depends(get_rag_service),
):
    """Send a message; reply is generated by Hybrid RAG only."""
    user_role = (request.context or {}).get("userRole") or (request.context or {}).get("user_role")
    log_chatbot_request(request.session_id, bool(user_role))

    if rag is None:
        log_chatbot_failure(request.session_id, "service not configured")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Chatbot service not configured",
        )
    reply = await rag.get_reply(db, message=request.content, user_role=user_role)
    log_chatbot_success(request.session_id)
    return ChatMessageResponse(
        message=reply,
        session_id=request.session_id,
        suggestions=[],
        actions=[],
    )


@router.post("/session", response_model=CreateSessionResponse)
async def create_session(request: CreateSessionRequest):
    """Create a new chat session."""
    import uuid
    session_id = f"session_{uuid.uuid4().hex[:12]}"
    return CreateSessionResponse(
        session_id=session_id,
        created_at=datetime.utcnow(),
    )


@router.get("/history", response_model=ChatHistoryResponse)
async def get_chat_history(session_id: str):
    """Get chat history for a session (stub: no persistence)."""
    return ChatHistoryResponse(session_id=session_id, messages=[])


@router.get("/health")
async def health_check():
    """Health check: 200 if chatbot is configured and ready, 503 if not (e.g. missing OPENAI_API_KEY)."""
    rag = get_rag_service()
    if rag is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Chatbot not configured. Set OPENAI_API_KEY in the backend .env and ensure FAQ data is loaded.",
        )
    return {"status": "healthy", "service": "chatbot"}
